
server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: ["localhost"]
      policy: one_factor

session:
  name: authelia_session
  secret: insecure_session_secret
  expiration: 3600
  inactivity: 300
  domain: localhost

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
