services:
  # -------------------- TRAEFIK (REVERSE PROXY) --------------------
  traefik:
    image: traefik:v3.0
    container_name: traefik
    user: "0" # Garante permissões para ler os certificados
    command:
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--providers.file.filename=/etc/traefik/config/dynamic.yml"
      - "--providers.file.watch=true"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic.yml:/etc/traefik/config/dynamic.yml:ro
      - ./traefik/certs:/certs:ro
    networks:
      - proxy
      - nginx-net
    depends_on:
      authentik-server:
        condition: service_healthy # Espera que o authentik-server esteja saudável
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.juarez.local`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=authentik@docker"

  # -------------------- AUTHENTIK (SSO) --------------------
  authentik-postgres:
    image: postgres:15-alpine
    container_name: authentik-postgres
    restart: unless-stopped
    # CORREÇÃO: Usa o ficheiro de configuração para desativar a autenticação por palavra-passe
    command: postgres -c 'hba_file=/etc/postgresql/pg_hba.conf'
    volumes:
      - authentik-db:/var/lib/postgresql/data
      - ./postgres-config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    environment:
      # Palavras-passe já não são necessárias aqui, mas mantemos o utilizador e a base de dados
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
    healthcheck: # Verifica se a base de dados está pronta
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - authentik-internal

  authentik-redis:
    image: redis:alpine
    container_name: authentik-redis
    restart: unless-stopped
    healthcheck: # Verifica se o redis está pronto
      test: ["CMD", "redis-cli", "ping"]
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - authentik-internal

  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-worker
    restart: unless-stopped
    user: "0"
    depends_on:
      authentik-postgres:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
    command: worker
    environment:
      AUTHENTIK_SECRET_KEY: "MUDE_A_SECRET_KEY_AQUI_PARA_ALGO_LONGO_E_SEGURO"
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      # A palavra-passe pode ser qualquer coisa ou vazia, pois o acesso é por 'trust'
      AUTHENTIK_POSTGRESQL__PASSWORD: ""
      AUTHENTIK_REDIS__HOST: authentik-redis
      TZ: "America/Sao_Paulo"
    volumes:
      - ./authentik/media:/media
      - ./authentik/templates:/templates
      - ./authentik/geoip:/geoip
    networks:
      - authentik-internal

  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-server
    restart: unless-stopped
    depends_on:
      authentik-worker:
        condition: service_started
    command: server
    environment:
      AUTHENTIK_SECRET_KEY: "MUDE_A_SECRET_KEY_AQUI_PARA_ALGO_LONGO_E_SEGURO"
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ""
      AUTHENTIK_REDIS__HOST: authentik-redis
      TZ: "America/Sao_Paulo"
    healthcheck: # Verifica se o authentik-server está pronto
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:9000/-/health/live/ || exit 1"]
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./authentik/media:/media
      - ./authentik/templates:/templates
      - ./authentik/geoip:/geoip
    networks:
      - proxy
      - authentik-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(`auth.juarez.local`)"
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.tls=true"
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"
      - "traefik.http.middlewares.authentik.forwardauth.address=http://authentik-server:9000/outpost.goauthentik.io/auth/traefik"
      - "traefik.http.middlewares.authentik.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authentik.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name"

  # -------------------- GUACAMOLE STACK --------------------
  guacamole-db:
    image: postgres:15-alpine
    container_name: guacamole-db
    restart: unless-stopped
    volumes:
      - guacamole-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: guacamole
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: "MUDE_A_SENHA_DO_BD_GUACAMOLE"
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - guacamole-internal

  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    networks:
      - guacamole-internal

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: unless-stopped
    depends_on:
      guacd:
        condition: service_started
      guacamole-db:
        condition: service_healthy
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: guacamole-db
      POSTGRESQL_DATABASE: guacamole
      POSTGRESQL_USER: guacamole_user
      POSTGRESQL_PASSWORD: "MUDE_A_SENHA_DO_BD_GUACAMOLE"
      TZ: "America/Sao_Paulo"
    networks:
      - proxy
      - guacamole-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.rule=Host(`guacamole.juarez.local`)"
      - "traefik.http.routers.guacamole.entrypoints=websecure"
      - "traefik.http.routers.guacamole.tls=true"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
      - "traefik.http.routers.guacamole.middlewares=authentik@docker"

  # -------------------- NGINX EM REDE SEPARADA --------------------
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - nginx-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nginx-net"
      - "traefik.http.routers.nginx.rule=Host(`nginx.juarez.local`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

# -------------------- DEFINIÇÃO DAS REDES E VOLUMES --------------------
networks:
  proxy:
    name: proxy
  authentik-internal:
    internal: true
  guacamole-internal:
    internal: true
  nginx-net:
    name: nginx-net

volumes:
  authentik-db:
  guacamole-db-data:
